### ISSUE TITLE
code to fix quotes with a fullstop at the beginning is a really cool implementation! just a minor error in variable declaration.

### ISSUE THREAD

**Issue by rooberrydev** [fac-17/Week3-BFPJ#36]
<img width="1440" alt="Screenshot 2019-07-19 at 10 34 05" src="https://user-images.githubusercontent.com/42008435/61526059-973c7b00-aa11-11e9-93d3-67a772386111.png">

The page does not load the quotes with a fullstop at the start, because trumpLowerCase is declared and given a value AFTER you're using it in the code.

```
var trumpData = JSON.parse(xhr.responseText);
      // fix quotes that start with a random full stop
      console.log(trumpData.value);
      if (trumpData.value.charAt(0) == ".") {
        trumpData.value = trumpData.value.slice(1, trumpLowerCase.length);
      }
      // filter obvious answers
      var trumpLowerCase = trumpData.value.toLowerCase();
```

when you assign
```trumpData.value = trumpData.value.slice(1, trumpLowerCase.length);```
trumpLowerCase.length will have a value of undefined,
because you are declaring trumpLowerCase further down in the code(using a variable before giving it a value).

The fix would be to declare trumpLowerCase before the if block.

```  var trumpData = JSON.parse(xhr.responseText);
     var trumpLowerCase = trumpData.value.toLowerCase();
      // fix quotes that start with a random full stop
      if (trumpData.value.charAt(0) == ".") {
        trumpData.value = trumpData.value.slice(1, trumpLowerCase.length);
      }```

**Comment by Coletterbox** [comment]
Thanks - yeah, I know you can't use a variable before having defined it. I wrote it normally, then rearranged some lines for "clarity" but clearly missed the fact that I hadn't only used that variable in the "filter" section.
